### ISSUE TITLE
复现咨询

### ISSUE THREAD

**Issue by XiaoYigwr** [liuheng92/tensorflow_PSENet#1]
您好，现在代码完全可以训练和测试吗？复现效果怎么样,与原作者的结果相差大吗？

**Comment by liuheng92** [comment]
可以的，已經有些網友跑了，你也可以試試，至於結果，我還在訓練，前不久寫完的

**Comment by XiaoYigwr** [comment]
谢谢，我在训练的时候将图片和对应的标签放在同一个文件夹下面，然后给定路径，发现在data_provider的get_batch(num_workers, **kwargs):函数中一直跳不出来，一直在循环，没有去训练，
                if not enqueuer.queue.empty():
                    generator_output = enqueuer.queue.get()
                    break
                else:
                    time.sleep(0.01)
发现一直进入到else中而没有进入到if not中，这是为何，如何做修改

**Comment by XiaoYigwr** [comment]
谢谢，您好，现在这个版本是上采样到原来的多少了，是1/8，还是1/4，还是1/2，还是原图大小？

**Comment by liuheng92** [comment]
> 谢谢，您好，现在这个版本是上采样到原来的多少了，是1/8，还是1/4，还是1/2，还是原图大小？

原图

**Comment by XiaoYigwr** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    
        谢谢
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                guowenrui_1314
                            
                    
                        
                            
                                    guowenrui_1314@sina.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2019年3月17日 11:04，Michael liu<notifications@github.com> 写道： 




谢谢，您好，现在这个版本是上采样到原来的多少了，是1/8，还是1/4，还是1/2，还是原图大小？



原图



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
