### ISSUE TITLE
数据集咨询

### ISSUE THREAD

**Issue by NormalAppler** [liuheng92/tensorflow_PSENet#11]
作者，你好，我再用天池数据进行训练的时候发现天池数据的txt中坐标值是逆时针排序的，而icdar2015中是按顺时针的，请问在训练的时候有必要将坐标转换为顺时针吗，现在训练并没有报错

**Comment by liuheng92** [comment]
不用，代码会自动转成顺时针

**Comment by wangshuai66666** [comment]
请问您用的天池哪个数据集？
