### ISSUE TITLE
 from .pse import pse_cpp  ImportError: dynamic module does not define module export function (PyInit_pse)

### ISSUE THREAD

**Issue by zealot5209** [liuheng92/tensorflow_PSENet#13]
I have modified Makefile for python3 but still got this error, plz help, thanks !

**Comment by liuheng92** [comment]
make sure you are using right python version, and enviroment,  could you provide more informations

**Comment by SimonsLiu** [comment]
> make sure you are using right python version, and enviroment, could you provide more informations

我好像也是编译那个pse出错


make: Entering directory '/media/liushihao/Ubuntu/tensorflow_PSENet-master/pse'
/usr/bin/g++ -o pse.so -I include  -std=c++11 -O3 -I/media/liushihao/Ubuntu/anaconda3/envs/deeplab3_TF/include/python3.6m -I/media/liushihao/Ubuntu/anaconda3/envs/deeplab3_TF/include/python3.6m  -Wno-unused-result -Wsign-compare -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O3 -pipe -fuse-linker-plugin -ffat-lto-objects -flto-partition=none -flto -DNDEBUG -fwrapv -O3 -Wall -Wstrict-prototypes -L/media/liushihao/Ubuntu/anaconda3/envs/deeplab3_TF/lib/python3.6/config-3.6m-x86_64-linux-gnu -L/media/liushihao/Ubuntu/anaconda3/envs/deeplab3_TF/lib -lpython3.6m -lpthread -ldl  -lutil -lrt -lm  -Xlinker -export-dynamic pse.cpp --shared -fPIC
g++: error: unrecognized command line option ‘-fno-plt’
Makefile:10: recipe for target 'pse.so' failed
make: *** [pse.so] Error 1
make: Leaving directory '/media/liushihao/Ubuntu/tensorflow_PSENet-master/pse'
Traceback (most recent call last):
  File "eval.py", line 18, in <module>
    from pse import pse
  File "/media/liushihao/Ubuntu/tensorflow_PSENet-master/pse/__init__.py", line 9, in <module>
    raise RuntimeError('Cannot compile pse: {}'.format(BASE_DIR))
RuntimeError: Cannot compile pse: /media/liushihao/Ubuntu/tensorflow_PSENet-master/pse

能不能帮我看看错误

**Comment by liuheng92** [comment]
[issues 5](https://github.com/liuheng92/tensorflow_PSENet/issues/5) may help you @SimonsLiu

**Comment by zealot5209** [comment]
> make sure you are using right python version, and enviroment, could you provide more informations

I'm using Python 3.6.3, tf 1.7.0,  my os is Centos 7

**Comment by Tian14267** [comment]
你是怎么解决你的问题的？因为我遇到一样的问题。不知道怎么修改Makefile。 @SimonsLiu

**Comment by fujingling** [comment]
change python3 to pyton2,  all problems will be solved, include this issue.

**Comment by cvding** [comment]
> 你是怎么解决你的问题的？因为我遇到一样的问题。不知道怎么修改Makefile。 @SimonsLiu
我的环境：python3， centos7 , miniconda3
直接修改Makefile
 在$(shell python-config --cflags) 后面添加 -I /home/xxx/miniconda3/include/python3.6m (这个可以通过python3-config --cflags命令获取到)

**Comment by Yangchao0053** [comment]
我这边用的python3.6,   Makefile 改成这样了：CXXFLAGS = -I include -std=c++11 -O3 $(shell python3.6-config --cflags)
LDFLAGS = $(shell python3.6-config --ldflags)
然后编译会报
g++: error: unrecognized command line option ‘-fno-plt’
这块有两种方式，一种是升级gcc，方式可参考： https://blog.csdn.net/menghuanbeike/article/details/79008640
我另一台机器6.4就可以编译，可是6.5还是有这个问题
另一种方式是：make以后，在下面的一大串命令中，把‘-fno-plt’去除，然后运行删除后的一大串命令，就编译出来.so了。
希望能帮到大家。

**Comment by MichaelHL-ai** [comment]
@Yangchao0053 thanks
