### ISSUE TITLE
Stuck during training, neither results nor error

### ISSUE THREAD

**Issue by liudatutu** [liuheng92/tensorflow_PSENet#14]
environment：Ubuntu 16.04
python 2.7.12
tensorflow 1.9.0
opencv 4.0
GPU：Tesla P100-PCIE-16GB *4

quesiton:
when i run the training,there is no result and no error,Always like this，why? ask for help,thanks.

this is my info:
t93@t93:~/liukui/tensorflow_PSENet$ python train.py --gpu_list=0,1,2,3 --input_size=8 --batch_size_per_gpu=1 --training_data_path=/home/t93/liukui/tensorflow_PSENet/data/train_data/ --learning_rate=0.01
DEBUG:matplotlib:CACHEDIR=/home/t93/.cache/matplotlib
DEBUG:matplotlib.font_manager:Using fontManager instance from /home/t93/.cache/matplotlib/fontList.json
DEBUG:matplotlib.backends:backend TkAgg version unknown
('resnet_v1_50/block1', TensorShape([Dimension(None), Dimension(None), Dimension(None), Dimension(256)]))
('resnet_v1_50/block2', TensorShape([Dimension(None), Dimension(None), Dimension(None), Dimension(512)]))
('resnet_v1_50/block3', TensorShape([Dimension(None), Dimension(None), Dimension(None), Dimension(1024)]))
('resnet_v1_50/block4', TensorShape([Dimension(None), Dimension(None), Dimension(None), Dimension(2048)]))
('resnet_v1_50/block1', TensorShape([Dimension(None), Dimension(None), Dimension(None), Dimension(256)]))
('resnet_v1_50/block2', TensorShape([Dimension(None), Dimension(None), Dimension(None), Dimension(512)]))
('resnet_v1_50/block3', TensorShape([Dimension(None), Dimension(None), Dimension(None), Dimension(1024)]))
('resnet_v1_50/block4', TensorShape([Dimension(None), Dimension(None), Dimension(None), Dimension(2048)]))
('resnet_v1_50/block1', TensorShape([Dimension(None), Dimension(None), Dimension(None), Dimension(256)]))
('resnet_v1_50/block2', TensorShape([Dimension(None), Dimension(None), Dimension(None), Dimension(512)]))
('resnet_v1_50/block3', TensorShape([Dimension(None), Dimension(None), Dimension(None), Dimension(1024)]))
('resnet_v1_50/block4', TensorShape([Dimension(None), Dimension(None), Dimension(None), Dimension(2048)]))
('resnet_v1_50/block1', TensorShape([Dimension(None), Dimension(None), Dimension(None), Dimension(256)]))
('resnet_v1_50/block2', TensorShape([Dimension(None), Dimension(None), Dimension(None), Dimension(512)]))
('resnet_v1_50/block3', TensorShape([Dimension(None), Dimension(None), Dimension(None), Dimension(1024)]))
('resnet_v1_50/block4', TensorShape([Dimension(None), Dimension(None), Dimension(None), Dimension(2048)]))
2019-04-18 08:37:04.457951: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-04-18 08:37:07.624170: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 0 with properties: 
name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:01:00.0
totalMemory: 15.89GiB freeMemory: 15.60GiB
2019-04-18 08:37:07.853845: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 1 with properties: 
name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:02:00.0
totalMemory: 15.89GiB freeMemory: 15.60GiB
2019-04-18 08:37:08.093972: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 2 with properties: 
name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:82:00.0
totalMemory: 15.89GiB freeMemory: 15.60GiB
2019-04-18 08:37:08.354169: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 3 with properties: 
name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:83:00.0
totalMemory: 15.89GiB freeMemory: 15.60GiB
2019-04-18 08:37:08.357313: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1471] Adding visible gpu devices: 0, 1, 2, 3
2019-04-18 08:37:09.640009: I tensorflow/core/common_runtime/gpu/gpu_device.cc:952] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-04-18 08:37:09.640055: I tensorflow/core/common_runtime/gpu/gpu_device.cc:958]      0 1 2 3 
2019-04-18 08:37:09.640063: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   N Y N N 
2019-04-18 08:37:09.640067: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 1:   Y N N N 
2019-04-18 08:37:09.640071: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 2:   N N N Y 
2019-04-18 08:37:09.640075: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 3:   N N Y N 
2019-04-18 08:37:09.641406: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15123 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:01:00.0, compute capability: 6.0)
2019-04-18 08:37:09.642872: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 15123 MB memory) -> physical GPU (device: 1, name: Tesla P100-PCIE-16GB, pci bus id: 0000:02:00.0, compute capability: 6.0)
2019-04-18 08:37:09.643928: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 15123 MB memory) -> physical GPU (device: 2, name: Tesla P100-PCIE-16GB, pci bus id: 0000:82:00.0, compute capability: 6.0)
2019-04-18 08:37:09.645089: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:3 with 15123 MB memory) -> physical GPU (device: 3, name: Tesla P100-PCIE-16GB, pci bus id: 0000:83:00.0, compute capability: 6.0)
INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/

**Comment by ccevan** [comment]
Hello, have you solved it?

**Comment by liudatutu** [comment]
@ccevan no,do you know why?

**Comment by ccevan** [comment]
@liudatutu 
Still not, I am trying to solve it.

**Comment by liuheng92** [comment]
stuck always?

**Comment by liudatutu** [comment]
@liuheng92 Yes, I tried on a different graphics card configuration server, like GTX1080Ti, while preventing input-size and batch_size_per_gpu from being too large, I narrowed it down to 1 and 64. But still stuck

**Comment by liuheng92** [comment]
I haven't encountered this problem. you can add some log in data generator file.

**Comment by xuweidongkobe** [comment]
@liudatutu Hello, have you solved it，I have the same problem？

**Comment by liudatutu** [comment]
@xuweidongkobe I haven't found the reason yet.

**Comment by ShanHaoYu** [comment]
Hi all, 
I also face this kind of problem.... 
Anyone has any idea?

**Comment by Wangweilai1** [comment]
I have the same problem，and I finded the Error positon, however don't know  how to correct.
![image](https://user-images.githubusercontent.com/15275988/59079808-0c4b6980-8918-11e9-92dd-c3634db6f50a.png)

**Comment by ahappycutedog** [comment]
@liudatutu hi , have you finally solved the problem?

**Comment by Finnis** [comment]
I have solved the problem. And I think this is caused by wrong dataset format. 
For example, I change the code in the picture bellow， and it works!
![image](https://user-images.githubusercontent.com/26062695/59332182-3d68d700-8d28-11e9-853a-b227ad4f410c.png)
By default, the code thought that the images and groundtruth.txt files are in the same directory. So you should specify the dir for your own dataset.

**Comment by rechardchen123** [comment]
> I have solved the problem. And I think this is caused by wrong dataset format.
> For example, I change the code in the picture bellow，which is in data_provider.py and it works!
> ![image](https://user-images.githubusercontent.com/26062695/59332182-3d68d700-8d28-11e9-853a-b227ad4f410c.png)
> By default, the code thought that the images and groundtruth.txt files are in the same directory. So you should specify the dir for your own dataset.

 I have already meet the same problem. May I ask you that what is the FLAGS.train_gt meaning? Should I need split the image and groundtruth.txt into different folders? And the train_gt is the address of the labels? Hope your reply！

**Comment by Finnis** [comment]
> 
> 
> > I have solved the problem. And I think this is caused by wrong dataset format.
> > For example, I change the code in the picture bellow，which is in data_provider.py and it works!
> > ![image](https://user-images.githubusercontent.com/26062695/59332182-3d68d700-8d28-11e9-853a-b227ad4f410c.png)
> > By default, the code thought that the images and groundtruth.txt files are in the same directory. So you should specify the dir for your own dataset.
> 
> I have already meet the same problem. May I ask you that what is the FLAGS.train_gt meaning? Should I need split the image and groundtruth.txt into different folders? And the train_gt is the address of the labels? Hope your reply！

Yes, FLAGS.train_gt is the directory of the train_gts, and the file tree of mine is like follow:
![image](https://user-images.githubusercontent.com/26062695/59399932-5628c980-8dc8-11e9-8c06-59d49cc66fe4.png)

**Comment by rechardchen123** [comment]
> > > I have solved the problem. And I think this is caused by wrong dataset format.
> > > For example, I change the code in the picture bellow，which is in data_provider.py and it works!
> > > ![image](https://user-images.githubusercontent.com/26062695/59332182-3d68d700-8d28-11e9-853a-b227ad4f410c.png)
> > > By default, the code thought that the images and groundtruth.txt files are in the same directory. So you should specify the dir for your own dataset.
> > 
> > 
> > I have already meet the same problem. May I ask you that what is the FLAGS.train_gt meaning? Should I need split the image and groundtruth.txt into different folders? And the train_gt is the address of the labels? Hope your reply！
> 
> Yes, FLAGS.train_gt is the directory of the train_gts, and the file tree of mine is like follow:
> ![image](https://user-images.githubusercontent.com/26062695/59399932-5628c980-8dc8-11e9-8c06-59d49cc66fe4.png)

Thanks for your reply and I have successfully realized it. Cheers!

**Comment by rechardchen123** [comment]
> > > I have solved the problem. And I think this is caused by wrong dataset format.
> > > For example, I change the code in the picture bellow，which is in data_provider.py and it works!
> > > ![image](https://user-images.githubusercontent.com/26062695/59332182-3d68d700-8d28-11e9-853a-b227ad4f410c.png)
> > > By default, the code thought that the images and groundtruth.txt files are in the same directory. So you should specify the dir for your own dataset.
> > 
> > 
> > I have already meet the same problem. May I ask you that what is the FLAGS.train_gt meaning? Should I need split the image and groundtruth.txt into different folders? And the train_gt is the address of the labels? Hope your reply！
> 
> Yes, FLAGS.train_gt is the directory of the train_gts, and the file tree of mine is like follow:
> ![image](https://user-images.githubusercontent.com/26062695/59399932-5628c980-8dc8-11e9-8c06-59d49cc66fe4.png)

Would you please give me some instruction about how to werite the tf.app.flags.DEFINE_string('train_gt') in the data_provider.py. I write the address but it not take effect. Many thanks!

**Comment by Finnis** [comment]
> 
> 
> > > > I have solved the problem. And I think this is caused by wrong dataset format.
> > > > For example, I change the code in the picture bellow，which is in data_provider.py and it works!
> > > > ![image](https://user-images.githubusercontent.com/26062695/59332182-3d68d700-8d28-11e9-853a-b227ad4f410c.png)
> > > > By default, the code thought that the images and groundtruth.txt files are in the same directory. So you should specify the dir for your own dataset.
> > > 
> > > 
> > > I have already meet the same problem. May I ask you that what is the FLAGS.train_gt meaning? Should I need split the image and groundtruth.txt into different folders? And the train_gt is the address of the labels? Hope your reply！
> > 
> > 
> > Yes, FLAGS.train_gt is the directory of the train_gts, and the file tree of mine is like follow:
> > ![image](https://user-images.githubusercontent.com/26062695/59399932-5628c980-8dc8-11e9-8c06-59d49cc66fe4.png)
> 
> Would you please give me some instruction about how to werite the tf.app.flags.DEFINE_string('train_gt') in the data_provider.py. I write the address but it not take effect. Many thanks!

For my case, it's like:
![image](https://user-images.githubusercontent.com/26062695/59545735-5b674f00-8f55-11e9-8974-d4ea75c2d338.png)

**Comment by rechardchen123** [comment]
> environment：Ubuntu 16.04
> python 2.7.12
> tensorflow 1.9.0
> opencv 4.0
> GPU：Tesla P100-PCIE-16GB *4
> 
> quesiton:
> when i run the training,there is no result and no error,Always like this，why? ask for help,thanks.
> 
> this is my info:
> t93@t93:~/liukui/tensorflow_PSENet$ python train.py --gpu_list=0,1,2,3 --input_size=8 --batch_size_per_gpu=1 --training_data_path=/home/t93/liukui/tensorflow_PSENet/data/train_data/ --learning_rate=0.01
> DEBUG:matplotlib:CACHEDIR=/home/t93/.cache/matplotlib
> DEBUG:matplotlib.font_manager:Using fontManager instance from /home/t93/.cache/matplotlib/fontList.json
> DEBUG:matplotlib.backends:backend TkAgg version unknown
> ('resnet_v1_50/block1', TensorShape([Dimension(None), Dimension(None), Dimension(None), Dimension(256)]))
> ('resnet_v1_50/block2', TensorShape([Dimension(None), Dimension(None), Dimension(None), Dimension(512)]))
> ('resnet_v1_50/block3', TensorShape([Dimension(None), Dimension(None), Dimension(None), Dimension(1024)]))
> ('resnet_v1_50/block4', TensorShape([Dimension(None), Dimension(None), Dimension(None), Dimension(2048)]))
> ('resnet_v1_50/block1', TensorShape([Dimension(None), Dimension(None), Dimension(None), Dimension(256)]))
> ('resnet_v1_50/block2', TensorShape([Dimension(None), Dimension(None), Dimension(None), Dimension(512)]))
> ('resnet_v1_50/block3', TensorShape([Dimension(None), Dimension(None), Dimension(None), Dimension(1024)]))
> ('resnet_v1_50/block4', TensorShape([Dimension(None), Dimension(None), Dimension(None), Dimension(2048)]))
> ('resnet_v1_50/block1', TensorShape([Dimension(None), Dimension(None), Dimension(None), Dimension(256)]))
> ('resnet_v1_50/block2', TensorShape([Dimension(None), Dimension(None), Dimension(None), Dimension(512)]))
> ('resnet_v1_50/block3', TensorShape([Dimension(None), Dimension(None), Dimension(None), Dimension(1024)]))
> ('resnet_v1_50/block4', TensorShape([Dimension(None), Dimension(None), Dimension(None), Dimension(2048)]))
> ('resnet_v1_50/block1', TensorShape([Dimension(None), Dimension(None), Dimension(None), Dimension(256)]))
> ('resnet_v1_50/block2', TensorShape([Dimension(None), Dimension(None), Dimension(None), Dimension(512)]))
> ('resnet_v1_50/block3', TensorShape([Dimension(None), Dimension(None), Dimension(None), Dimension(1024)]))
> ('resnet_v1_50/block4', TensorShape([Dimension(None), Dimension(None), Dimension(None), Dimension(2048)]))
> 2019-04-18 08:37:04.457951: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
> 2019-04-18 08:37:07.624170: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 0 with properties:
> name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
> pciBusID: 0000:01:00.0
> totalMemory: 15.89GiB freeMemory: 15.60GiB
> 2019-04-18 08:37:07.853845: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 1 with properties:
> name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
> pciBusID: 0000:02:00.0
> totalMemory: 15.89GiB freeMemory: 15.60GiB
> 2019-04-18 08:37:08.093972: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 2 with properties:
> name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
> pciBusID: 0000:82:00.0
> totalMemory: 15.89GiB freeMemory: 15.60GiB
> 2019-04-18 08:37:08.354169: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 3 with properties:
> name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
> pciBusID: 0000:83:00.0
> totalMemory: 15.89GiB freeMemory: 15.60GiB
> 2019-04-18 08:37:08.357313: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1471] Adding visible gpu devices: 0, 1, 2, 3
> 2019-04-18 08:37:09.640009: I tensorflow/core/common_runtime/gpu/gpu_device.cc:952] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2019-04-18 08:37:09.640055: I tensorflow/core/common_runtime/gpu/gpu_device.cc:958] 0 1 2 3
> 2019-04-18 08:37:09.640063: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0: N Y N N
> 2019-04-18 08:37:09.640067: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 1: Y N N N
> 2019-04-18 08:37:09.640071: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 2: N N N Y
> 2019-04-18 08:37:09.640075: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 3: N N Y N
> 2019-04-18 08:37:09.641406: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15123 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:01:00.0, compute capability: 6.0)
> 2019-04-18 08:37:09.642872: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 15123 MB memory) -> physical GPU (device: 1, name: Tesla P100-PCIE-16GB, pci bus id: 0000:02:00.0, compute capability: 6.0)
> 2019-04-18 08:37:09.643928: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 15123 MB memory) -> physical GPU (device: 2, name: Tesla P100-PCIE-16GB, pci bus id: 0000:82:00.0, compute capability: 6.0)
> 2019-04-18 08:37:09.645089: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:3 with 15123 MB memory) -> physical GPU (device: 3, name: Tesla P100-PCIE-16GB, pci bus id: 0000:83:00.0, compute capability: 6.0)
> INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
> INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
> INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
> INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
> INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
> INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
> INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
> INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
> INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
> INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
> INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
> INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
> INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
> INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
> INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
> INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
> INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
> INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
> INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
> INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
> INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
> INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
> INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
> INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
> INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
> INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
> INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
> INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
> INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
> INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
> INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/
> INFO:root:10048 training images in /home/t93/liukui/tensorflow_PSENet/data/train_data/

I have also meet the same problem with you like 'INFO:root:....'. And I have tested a lot of method and have found that the dataset may rise this phenomenon. Please check your dataset format especially the gt_files. And check your data_provider.py, the `txt_fn = im_fn.replace(os.path.basename(im_fn).split('.')[1], 'txt')` shoud the name be coordinated with your insider gt_files. Please check it.

**Comment by donglin8506** [comment]
@rechardchen123 Firstly --training_data_path isn't in 'train.py' file ,  but in  /utils/data_provider/data_provider.py.
![Screenshot from 2019-07-04 18-22-55](https://user-images.githubusercontent.com/41879987/60659798-dce13b80-9e88-11e9-978c-26c59eaf645e.png)

1) In line 16 , please modify your own training_data_path. 
2) And Please note that all train images and  corresponding groundtruths need to be in the same folder.
3) Every image and corresponding groundtruth should have same name but don't include suffix. For example img_1.jpg and img_1.txt.
4) Then run `python train.py --checkpoint_path=$model_folder` ($model_folder)
For example,
![image](https://user-images.githubusercontent.com/41879987/60660615-b3291400-9e8a-11e9-9a40-5b2825a33240.png)
![image](https://user-images.githubusercontent.com/41879987/60660860-44988600-9e8b-11e9-87ae-df842313e9b8.png)
Note that file 'checkpoint' needs to be created by yourself.

Good luck!

**Comment by rechardchen123** [comment]
> @rechardchen123 Firstly --training_data_path isn't in 'train.py' file , but in /utils/data_provider/data_provider.py.
> ![Screenshot from 2019-07-04 18-22-55](https://user-images.githubusercontent.com/41879987/60659798-dce13b80-9e88-11e9-978c-26c59eaf645e.png)
> 
> 1. In line 16 , please modify your own training_data_path.
> 2. And Please note that all train images and  corresponding groundtruths need to be in the same folder.
> 3. Every image and corresponding groundtruth should have same name but don't include suffix. For example img_1.jpg and img_1.txt.
> 4. Then run `python train.py --checkpoint_path=$model_folder` ($model_folder)
>    For example,
>    ![image](https://user-images.githubusercontent.com/41879987/60660615-b3291400-9e8a-11e9-9a40-5b2825a33240.png)
>    ![image](https://user-images.githubusercontent.com/41879987/60660860-44988600-9e8b-11e9-87ae-df842313e9b8.png)
>    Note that file 'checkpoint' needs to be created by yourself.
> 
> Good luck!

Thanks donglin8506. I have already solved the issue and thanks for your answer. It is quite useful for the other person who have the same problems.
