### ISSUE TITLE
undefined symbol: _Py_ZeroStruct问题

### ISSUE THREAD

**Issue by wangshuai66666** [liuheng92/tensorflow_PSENet#15]
我修改了makefile里的python3-config，run eval.py，还是报错这个问题。请求帮助。 @liuheng92

**Comment by wangshuai66666** [comment]
File "/home/ws/sfz1/PSENet/pse/__init__.py", line 17, in pse
    from .pse import pse_cpp
ImportError: /home/ws/sfz1/PSENet/pse/pse.so: undefined symbol: _Py_ZeroStruct
请问这怎么解决？

**Comment by wangshuai66666** [comment]
我的python3.6是用anaconda3装的

**Comment by liuheng92** [comment]
你确认一下是否用anaconda3的环境编译的，这个你可以从makefile中打印一下，然后跑的时候确认一下是否是同一个环境跑的

**Comment by wangshuai66666** [comment]
谢谢！我已经自己解决了。首先要升级自己的GCC版本到6，然后注意python3和2的问题，我的是用python3.6-config代替python-config，还有将xrange( )函数全部换为range( )。
有一个新问题，如果我想检测身份证或银行卡上的文本，怎么考虑呢？是要重新选择训练集训练吗？我用您的模型试过身份证和银行卡了，有些检测效果不是很理想，所以想请您帮我分析一下。 @liuheng92

**Comment by liuheng92** [comment]
当然需要对应的训练集重新训练，你可以网上搜，或者自己造一些样本

**Comment by wangshuai66666** [comment]
能否提供一个下载ICDAR2017数据集的网址？网上找了好多都不能下载 @liuheng92

**Comment by softwaregitgub** [comment]
谢谢@liuheng92 ，我用的python3.6 将makefile里的python-config 换成python3-config，然后通过命令激活anaconda3里的python3.6的虚拟环境，运行如下解决了：
(tf) stay@stay-N8xEJEK:~/Desktop/tensorflowPSENet$ python eval.py

**Comment by wuzuowuyou** [comment]
将Makefile文件的以下行

CXXFLAGS = -I include  -std=c++11 -O3 $(shell python3-config --cflags)

中的$(shell python3-config --cflags)替换为

-I/home/xx/anaconda3/include/python3.6m

注意：替换的部分请换成自己的anaconda目录，如果不知道按照在哪，可以通过在命令行输入python3-config --cflags，然后回车看到，anaconda路径
