### ISSUE TITLE
About "checkpoint" file

### ISSUE THREAD

**Issue by SuperYanyann** [liuheng92/tensorflow_PSENet#19]
Hi, I want to test the model on my dataset. After I downloaded your model from baiduyun, I found that there are only three files in the folder, there is no "checkpoint" file. I want to know if this is caused by my download error? thanks.

**Comment by SuperYanyann** [comment]
I get it.

**Comment by Melvin-leo** [comment]
Can you explain how you get it? I experience that too and I am new to tensorflow but I do not know about this checkpoint files, Thank you!

**Comment by sukhad-app** [comment]
How did you figure it out ?
