### ISSUE TITLE
关于训练集

### ISSUE THREAD

**Issue by xdwjc** [liuheng92/tensorflow_PSENet#2]
博主您好 十分佩服您能复现出这个代码，小弟有一个问题想请教一下您，您放的百度云链接你训练好的模型是只在1000张的icdar2015上训练出来的，还是在icdar2015+icdar2017-mlt 8000多张上训练出来的

**Comment by liuheng92** [comment]
> 博主您好 十分佩服您能复现出这个代码，小弟有一个问题想请教一下您，您放的百度云链接你训练好的模型是只在1000张的icdar2015上训练出来的，还是在icdar2015+icdar2017-mlt 8000多张上训练出来的

icdar2015+mlt 8000多张的结果

**Comment by xdwjc** [comment]
好的，谢谢博主
