### ISSUE TITLE
 No module named 'pse.pse'

### ISSUE THREAD

**Issue by mpd847** [liuheng92/tensorflow_PSENet#21]
from .pse import pse_cpp
ModuleNotFoundError: No module named 'pse.pse'

i couldn't use the pse_cpp module ? 
is compiling pse is necessesary!! i am getting file not found error in subprocess?
can anyone please help me

**Comment by JingCi-ZHu** [comment]
I have got the same error, have you finished it?

**Comment by mpd847** [comment]
Open the x64 or x32 Visual Studio devloper command prompt in Windows 10 and use the following command to generate the pse.pyd file:
first cd into pse folder
cl pse.cpp /I ./include /I "C:\Users\risha\Anaconda3\include" /LD /Fe:pse.pyd /link/LIBPATH:"C:\Users\risha\Anaconda3\libs"
comment line 8 and 9 of init.py

this fixed the issue.

**Comment by JingCi-ZHu** [comment]
thank you for your answer, I have tried it,but I cant generate the pse.pyd file 
![image](https://user-images.githubusercontent.com/45458068/60259195-47363100-9909-11e9-9bb3-66f82921b84f.png)
have you seen that?

**Comment by mpd847** [comment]
no i didn't get any fatal error. try with another python version

**Comment by JingCi-ZHu** [comment]
thank you very much, I success to test !!!!!!!!!!!!!

**Comment by ZDDEAN** [comment]
> 非常感谢，我成功地测试!!!!!!!!!!!!!
我编译也出错了，请问你怎么做的呀

**Comment by xiakj** [comment]
谢谢，可以生成pse.pyd，只不过vs的编译工具要用x64位的（我的）。
