### ISSUE TITLE
where can i find pse_cpp ??

### ISSUE THREAD

**Issue by mpd847** [liuheng92/tensorflow_PSENet#22]
can anyone tell me how to compile pse ??
where can i find pse_cpp ?
i am getting this error when i make the file from cmd
---------------------------------------------------------------------
FIND: Parameter format not correct
process_begin: CreateProcess(NULL, python3-config --cflags, ...) failed.
process_begin: CreateProcess(NULL, python3-config --ldflags, ...) failed.
g++ -o pse.so -I include  -std=gnu++0x -O3   pse.cpp --shared -fPIC
C:\Users\xxx\AppData\Local\Temp\ccum3Drs.o:pse.cpp:(.text$_ZZN8pybind116detail13get_internalsEvENKUlNSt15__exception_ptr13exception_ptrEE_clES2_[__ZZN8pybind116detail13get_internalsEvENKUlNSt15__exception_ptr13exception_ptrEE_clES2_]+0x16c): undefined reference to `_imp__PyErr_SetString'
C:\Users\xxx\AppData\Local\Temp\ccum3Drs.o:pse.cpp:(.text$_ZN8pybind1118gil_scoped_acquire7dec_refEv[__ZN8pybind1118gil_scoped_acquire7dec_refEv]+0x4e): undefined reference to
`_imp__PyThread_set_key_value'
C:\Users\xxx\AppData\Local\Temp\ccum3Drs.o:pse.cpp:(.text$_ZN8pybind1112cpp_function10dispatcherEP7_objectS2_S2_[__ZN8pybind1112cpp_function10dispatcherEP7_objectS2_S2_]+0xd7a): undefined reference to `_imp__PyTuple_SetItem'
C:\Users\xxx\AppData\Local\Temp\ccum3Drs.o:pse.cpp:(.text$_ZN8pybind1112cpp_function10dispatcherEP7_objectS2_S2_[__ZN8pybind1112cpp_function10dispatcherEP7_objectS2_S2_]+0xeb1): undefined reference to `_imp___Py_NoneStruct'
C:\Users\xxx\AppData\Local\Temp\ccum3Drs.o:pse.cpp:(.text$_ZN8pybind1112cpp_function10dispatcherEP7_objectS2_S2_[__ZN8pybind1112cpp_function10dispatcherEP7_objectS2_S2_]+0xf5e): undefined reference to `_imp__PyDict_New'
C:\Users\xxx\AppData\Local\Temp\ccum3Drs.o:pse.cpp:(.text$_ZN8pybind1112cpp_function10dispatcherEP7_objectS2_S2_[__ZN8pybind1112cpp_function10dispatcherEP7_objectS2_S2_]+0x1010): undefined reference to `_imp___Py_NotImplementedStruct'
C:\Users\xxx\AppData\Local\Temp\ccum3Drs.o:pse.cpp:(.text$_ZN8pybind1112cpp_function10dispatcherEP7_objectS2_S2_[__ZN8pybind1112cpp_function10dispatcherEP7_objectS2_S2_]+0x147d): undefined reference to `_imp__PyTuple_Size'
C:\Users\xxx\AppData\Local\Temp\ccum3Drs.o:pse.cpp:(.text$_ZN8pybind1112cpp_function10dispatcherEP7_objectS2_S2_[__ZN8pybind1112cpp_function10dispatcherEP7_objectS2_S2_]+0x14ae): undefined reference to `_imp__PyTuple_GetItem'
C:\Users\xxx\AppData\Local\Temp\ccum3Drs.o:pse.cpp:(.text$_ZN8pybind1112cpp_function10dispatcherEP7_objectS2_S2_[__ZN8pybind1112cpp_function10dispatcherEP7_objectS2_S2_]+0x14c4): undefined reference to `_imp__PyObject_Repr'
C:\Users\xxx\AppData\Local\Temp\ccum3Drs.o:pse.cpp:(.text$_ZN8pybind1112cpp_function10dispatcherEP7_objectS2_S2_[__ZN8pybind1112cpp_function10dispatcherEP7_objectS2_S2_]+0x1579): undefined reference to `_imp__PyDict_Size'
C:\Users\xxx\AppData\Local\Temp\ccum3Drs.o:pse.cpp:(.text$_ZN8pybind1112cpp_function10dispatcherEP7_objectS2_S2_[__ZN8pybind1112cpp_function10dispatcherEP7_objectS2_S2_]+0x15dc): undefined reference to `_imp__PyDict_Next'
C:\Users\xxx\AppData\Local\Temp\ccum3Drs.o:pse.cpp:(.text$_ZN8pybind1112cpp_function10dispatcherEP7_objectS2_S2_[__ZN8pybind1112cpp_function10dispatcherEP7_objectS2_S2_]+0x168d): undefined reference to `_imp__PyObject_CallObject'
C:\Users\xxx\AppData\Local\Temp\ccum3Drs.o:pse.cpp:(.text$_ZN8pybind1112cpp_function10dispatcherEP7_objectS2_S2_[__ZN8pybind1112cpp_function10dispatcherEP7_objectS2_S2_]+0x17d2): undefined reference to `_imp__PyExc_TypeError'
C:\Users\xxx\AppData\Local\Temp\ccum3Drs.o:pse.cpp:(.text$_ZN8pybind1112cpp_function10dispatcherEP7_objectS2_S2_[__ZN8pybind1112cpp_function10dispatcherEP7_objectS2_S2_]+0x17dd): undefined reference to `_imp__PyErr_SetString'
C:\Users\xxx\AppData\Local\Temp\ccum3Drs.o:pse.cpp:(.text$_ZN8pybind1112cpp_function10dispatcherEP7_objectS2_S2_[__ZN8pybind1112cpp_function10dispatcherEP7_objectS2_S2_]+0x1947): undefined reference to `_imp__PyErr_Restore'
C:\Users\xxx\AppData\Local\Temp\ccum3Drs.o:pse.cpp:(.text$_ZN8pybind1112cpp_function10dispatcherEP7_objectS2_S2_[__ZN8pybind1112cpp_function10dispatcherEP7_objectS2_S2_]+0x19da): undefined reference to `_imp__PyExc_TypeError'
C:\Users\xxx\AppData\Local\Temp\ccum3Drs.o:pse.cpp:(.text$_ZN8pybind1112cpp_function10dispatcherEP7_objectS2_S2_[__ZN8pybind1112cpp_function10dispatcherEP7_objectS2_S2_]+0x19ef): undefined reference to `_imp__PyErr_SetString'
C:\Users\xxx\AppData\Local\Temp\ccum3Drs.o:pse.cpp:(.text$_ZN8pybind1112cpp_function10dispatcherEP7_objectS2_S2_[__ZN8pybind1112cpp_function10dispatcherEP7_objectS2_S2_]+0x1d6f): undefined reference to `_imp__PyExc_SystemError'
C:\Users\xxx\AppData\Local\Temp\ccum3Drs.o:pse.cpp:(.text$_ZN8pybind1112cpp_function10dispatcherEP7_objectS2_S2_[__ZN8pybind1112cpp_function10dispatcherEP7_objectS2_S2_]+0x1d82): undefined reference to `_imp__PyErr_SetString'
C:\Users\xxx\AppData\Local\Temp\ccum3Drs.o:pse.cpp:(.text$_ZN8pybind1112cpp_function10dispatcherEP7_objectS2_S2_[__ZN8pybind1112cpp_function10dispatcherEP7_objectS2_S2_]+0x1e11): undefined reference to `_imp__PyExc_TypeError'
C:\Users\xxx\AppData\Local\Temp\ccum3Drs.o:pse.cpp:(.text$_ZN8pybind1112cpp_function10dispatcherEP7_objectS2_S2_[__ZN8pybind1112cpp_function10dispatcherEP7_objectS2_S2_]+0x1e1c): undefined reference to `_imp__PyErr_SetString'
C:\Users\xxx\AppData\Local\Temp\ccum3Drs.o:pse.cpp:(.text$_ZN8pybind116detail8instance15allocate_layoutEv[__ZN8pybind116detail8instance15allocate_layoutEv]+0xed): undefined reference to `_imp__PyWeakref_NewRef'
C:\Users\xxx\AppData\Local\Temp\ccum3Drs.o:pse.cpp:(.text$_ZN8pybind116detail8instance15allocate_layoutEv[__ZN8pybind116detail8instance15allocate_layoutEv]+0x187): undefined reference to `_imp__PyMem_Calloc'
C:\Users\xxx\AppData\Local\Temp\ccum3Drs.o:pse.cpp:(.text$_ZN8pybind116detail14clear_instanceEP7_object[__ZN8pybind116detail14clear_instanceEP7_object]+0xee): undefined reference to `_imp__PyWeakref_NewRef'
C:\Users\xxx\AppData\Local\Temp\ccum3Drs.o:pse.cpp:(.text$_ZN8pybind116detail14clear_instanceEP7_object[__ZN8pybind116detail14clear_instanceEP7_object]+0x68b): undefined reference to `_imp__PyObject_ClearWeakRefs'
C:\Users\xxx\AppData\Local\Temp\ccum3Drs.o:pse.cpp:(.text$_ZN8pybind116detail14clear_instanceEP7_object[__ZN8pybind116detail14clear_instanceEP7_object]+0x697): undefined reference to `_imp___PyObject_GetDictPtr'
C:\Users\xxx\AppData\Local\Temp\ccum3Drs.o:pse.cpp:(.text$_ZZN8pybind1112cpp_function10initializeIZNS_6detail23all_type_info_get_cacheEP11_typeobjectEUlNS_6handleEE_vJS5_EJEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS2_13function_callEE1_4_FUNESJ_[__ZZN8pybind1112cpp_function10initializeIZNS_6detail23all_type_info_get_cacheEP11_typeobjectEUlNS_6handleEE_vJS5_EJEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS2_13function_callEE1_4_FUNESJ_]+0x8a): undefined reference to `_imp___Py_NoneStruct'
C:\Users\xxx\AppData\Local\Temp\ccum3Drs.o:pse.cpp:(.text$_ZZN8pybind1112cpp_function10initializeIZNS_6detail23all_type_info_get_cacheEP11_typeobjectEUlNS_6handleEE_vJS5_EJEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS2_13function_callEE1_4_FUNESJ_[__ZZN8pybind1112cpp_function10initializeIZNS_6detail23all_type_info_get_cacheEP11_typeobjectEUlNS_6handleEE_vJS5_EJEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS2_13function_callEE1_4_FUNESJ_]+0xfb): undefined reference to `_imp___Py_NoneStruct'
C:\Users\xxx\AppData\Local\Temp\ccum3Drs.o:pse.cpp:(.text$_ZN8pybind116detail11type_casterIivE4loadENS_6handleEb[__ZN8pybind116detail11type_casterIivE4loadENS_6handleEb]+0x18): undefined reference to `_imp__PyFloat_Type'
C:\Users\xxx\AppData\Local\Temp\ccum3Drs.o:pse.cpp:(.text$_ZN8pybind116detail11type_casterIivE4loadENS_6handleEb[__ZN8pybind116detail11type_casterIivE4loadENS_6handleEb]+0x2b): undefined reference to `_imp__PyType_IsSubtype'
C:\Users\xxx\AppData\Local\Temp\ccum3Drs.o:pse.cpp:(.text$_ZN8pybind116detail11type_casterIivE4loadENS_6handleEb[__ZN8pybind116detail11type_casterIivE4loadENS_6handleEb]+0x45): undefined reference to `_imp__PyLong_AsLong'
C:\Users\xxx\AppData\Local\Temp\ccum3Drs.o:pse.cpp:(.text$_ZN8pybind116detail11type_casterIivE4loadENS_6handleEb[__ZN8pybind116detail11type_casterIivE4loadENS_6handleEb]+0x67): undefined reference to `_imp__PyErr_Occurred'
C:\Users\xxx\AppData\Local\Temp\ccum3Drs.o:pse.cpp:(.text$_ZN8pybind116detail11type_casterIivE4loadENS_6handleEb[__ZN8pybind116detail11type_casterIivE4loadENS_6handleEb]+0x70): undefined reference to `_imp__PyExc_TypeError'
C:\Users\xxx\AppData\Local\Temp\ccum3Drs.o:pse.cpp:(.text$_ZN8pybind116detail11type_casterIivE4loadENS_6handleEb[__ZN8pybind116detail11type_casterIivE4loadENS_6handleEb]+0x7b): undefined reference to `_imp__PyErr_ExceptionMatches'
C:\Users\xxx\AppData\Local\Temp\ccum3Drs.o:pse.cpp:(.text$_ZN8pybind116detail11type_casterIivE4loadENS_6handleEb[__ZN8pybind116detail11type_casterIivE4loadENS_6handleEb]+0x85): undefined reference to `_imp__PyErr_Clear'
C:\Users\Zebi\AppData\Local\Temp\ccum3Drs.o:pse.cpp:(.text$_ZN8pybind116detail11type_casterIivE4loadENS_6handleEb[__ZN8pybind116detail11type_casterIivE4loadENS_6handleEb]+0x91): undefined reference to `_imp__PyErr_Clear'
C:\Users\xxx\AppData\Local\Temp\ccum3Drs.o:pse.cpp:(.text$_ZN8pybind116detail11type_casterIivE4loadENS_6handleEb[__ZN8pybind116detail11type_casterIivE4loadENS_6handleEb]+0xa5): undefined reference to `_imp__PyNumber_Check'
C:\Users\Zebi\AppData\Local\Temp\ccum3Drs.o:pse.cpp:(.text$_ZN8pybind116detail11type_casterIivE4loadENS_6handleEb[__ZN8pybind116detail11type_casterIivE4loadENS_6handleEb]+0xb2): undefined reference to `_imp__PyNumber_Long'
C:\Users\xxx\AppData\Local\Temp\ccum3Drs.o:pse.cpp:(.text$_ZZN8pybind1112cpp_function10initializeIRPFSt6vectorIS2_IiSaIiEESaIS4_EENS_7array_tIiLi1EEENS7_IhLi1EEEiES6_JS8_S9_iEJNS_4nameENS_5scopeENS_7siblingEA38_cNS_3argESH_NS_5arg_vEEEEvOT_PFT0_DpT1_EDpRKT2_ENKUlRNS_6detail13function_callEE1_clESW_[__ZZN8pybind1112cpp_function10initializeIRPFSt6vectorIS2_IiSaIiEESaIS4_EENS_7array_tIiLi1EEENS7_IhLi1EEEiES6_JS8_S9_iEJNS_4nameENS_5scopeENS_7siblingEA38_cNS_3argESH_NS_5arg_vEEEEvOT_PFT0_DpT1_EDpRKT2_ENKUlRNS_6detail13function_callEE1_clESW_]+0x33c): undefined reference to `_imp__PyList_New'
C:\Users\xxx\AppData\Local\Temp\ccum3Drs.o:pse.cpp:(.text$_ZZN8pybind1112cpp_function10initializeIRPFSt6vectorIS2_IiSaIiEESaIS4_EENS_7array_tIiLi1EEENS7_IhLi1EEEiES6_JS8_S9_iEJNS_4nameENS_5scopeENS_7siblingEA38_cNS_3argESH_NS_5arg_vEEEEvOT_PFT0_DpT1_EDpRKT2_ENKUlRNS_6detail13function_callEE1_clESW_[__ZZN8pybind1112cpp_function10initializeIRPFSt6vectorIS2_IiSaIiEESaIS4_EENS_7array_tIiLi1EEENS7_IhLi1EEEiES6_JS8_S9_iEJNS_4nameENS_5scopeENS_7siblingEA38_cNS_3argESH_NS_5arg_vEEEEvOT_PFT0_DpT1_EDpRKT2_ENKUlRNS_6detail13function_callEE1_clESW_]+0x3c0): undefined reference to `_imp__PyLong_FromSsize_t'
C:\Users\xxx\AppData\Local\Temp\ccum3Drs.o:pse.cpp:(.text$_ZZN8pybind1112cpp_function10initializeIRPFSt6vectorIS2_IiSaIiEESaIS4_EENS_7array_tIiLi1EEENS7_IhLi1EEEiES6_JS8_S9_iEJNS_4nameENS_5scopeENS_7siblingEA38_cNS_3argESH_NS_5arg_vEEEEvOT_PFT0_DpT1_EDpRKT2_ENKUlRNS_6detail13function_callEE1_clESW_[__ZZN8pybind1112cpp_function10initializeIRPFSt6vectorIS2_IiSaIiEESaIS4_EENS_7array_tIiLi1EEENS7_IhLi1EEEiES6_JS8_S9_iEJNS_4nameENS_5scopeENS_7siblingEA38_cNS_3argESH_NS_5arg_vEEEEvOT_PFT0_DpT1_EDpRKT2_ENKUlRNS_6detail13function_callEE1_clESW_]+0x4d4): undefined reference to `_imp__PyType_IsSubtype'
C:\Users\xxx\AppData\Local\Temp\ccum3Drs.o:pse.cpp:(.text$_ZZN8pybind1112cpp_function10initializeIRPFSt6vectorIS2_IiSaIiEESaIS4_EENS_7array_tIiLi1EEENS7_IhLi1EEEiES6_JS8_S9_iEJNS_4nameENS_5scopeENS_7siblingEA38_cNS_3argESH_NS_5arg_vEEEEvOT_PFT0_DpT1_EDpRKT2_ENKUlRNS_6detail13function_callEE1_clESW_[__ZZN8pybind1112cpp_function10initializeIRPFSt6vectorIS2_IiSaIiEESaIS4_EENS_7array_tIiLi1EEENS7_IhLi1EEEiES6_JS8_S9_iEJNS_4nameENS_5scopeENS_7siblingEA38_cNS_3argESH_NS_5arg_vEEEEvOT_PFT0_DpT1_EDpRKT2_ENKUlRNS_6detail13function_callEE1_clESW_]+0x551): undefined reference to `_imp__PyType_IsSubtype'
C:\Users\xxx\AppData\Local\Temp\ccum3Drs.o:pse.cpp:(.text$_ZZN8pybind1112cpp_function10initializeIRPFSt6vectorIS2_IiSaIiEESaIS4_EENS_7array_tIiLi1EEENS7_IhLi1EEEiES6_JS8_S9_iEJNS_4nameENS_5scopeENS_7siblingEA38_cNS_3argESH_NS_5arg_vEEEEvOT_PFT0_DpT1_EDpRKT2_ENKUlRNS_6detail13function_callEE1_clESW_[__ZZN8pybind1112cpp_function10initializeIRPFSt6vectorIS2_IiSaIiEESaIS4_EENS_7array_tIiLi1EEENS7_IhLi1EEEiES6_JS8_S9_iEJNS_4nameENS_5scopeENS_7siblingEA38_cNS_3argESH_NS_5arg_vEEEEvOT_PFT0_DpT1_EDpRKT2_ENKUlRNS_6detail13function_callEE1_clESW_]+0x633): undefined reference to `_imp__PyExc_ValueError'
C:\Users\xxx\AppData\Local\Temp\ccum3Drs.o:pse.cpp:(.text$_ZZN8pybind1112cpp_function10initializeIRPFSt6vectorIS2_IiSaIiEESaIS4_EENS_7array_tIiLi1EEENS7_IhLi1EEEiES6_JS8_S9_iEJNS_4nameENS_5scopeENS_7siblingEA38_cNS_3argESH_NS_5arg_vEEEEvOT_PFT0_DpT1_EDpRKT2_ENKUlRNS_6detail13function_callEE1_clESW_[__ZZN8pybind1112cpp_function10initializeIRPFSt6vectorIS2_IiSaIiEESaIS4_EENS_7array_tIiLi1EEENS7_IhLi1EEEiES6_JS8_S9_iEJNS_4nameENS_5scopeENS_7siblingEA38_cNS_3argESH_NS_5arg_vEEEEvOT_PFT0_DpT1_EDpRKT2_ENKUlRNS_6detail13function_callEE1_clESW_]+0x646): undefined reference to `_imp__PyErr_SetString'
C:\Users\xxx\AppData\Local\Temp\ccum3Drs.o:pse.cpp:(.text$_ZZN8pybind1112cpp_function10initializeIRPFSt6vectorIS2_IiSaIiEESaIS4_EENS_7array_tIiLi1EEENS7_IhLi1EEEiES6_JS8_S9_iEJNS_4nameENS_5scopeENS_7siblingEA38_cNS_3argESH_NS_5arg_vEEEEvOT_PFT0_DpT1_EDpRKT2_ENKUlRNS_6detail13function_callEE1_clESW_[__ZZN8pybind1112cpp_function10initializeIRPFSt6vectorIS2_IiSaIiEESaIS4_EENS_7array_tIiLi1EEENS7_IhLi1EEEiES6_JS8_S9_iEJNS_4nameENS_5scopeENS_7siblingEA38_cNS_3argESH_NS_5arg_vEEEEvOT_PFT0_DpT1_EDpRKT2_ENKUlRNS_6detail13function_callEE1_clESW_]+0x64c): undefined reference to `_imp__PyErr_Clear'
C:\Users\xxx\AppData\Local\Temp\ccum3Drs.o:pse.cpp:(.text$_ZZN8pybind1112cpp_function10initializeIRPFSt6vectorIS2_IiSaIiEESaIS4_EENS_7array_tIiLi1EEENS7_IhLi1EEEiES6_JS8_S9_iEJNS_4nameENS_5scopeENS_7siblingEA38_cNS_3argESH_NS_5arg_vEEEEvOT_PFT0_DpT1_EDpRKT2_ENKUlRNS_6detail13function_callEE1_clESW_[__ZZN8pybind1112cpp_function10initializeIRPFSt6vectorIS2_IiSaIiEESaIS4_EENS_7array_tIiLi1EEENS7_IhLi1EEEiES6_JS8_S9_iEJNS_4nameENS_5scopeENS_7siblingEA38_cNS_3argESH_NS_5arg_vEEEEvOT_PFT0_DpT1_EDpRKT2_ENKUlRNS_6detail13function_callEE1_clESW_]+0x658): undefined reference to `_imp__PyExc_ValueError'
C:\Users\xxx\AppData\Local\Temp\ccum3Drs.o:pse.cpp:(.text$_ZZN8pybind1112cpp_function10initializeIRPFSt6vectorIS2_IiSaIiEESaIS4_EENS_7array_tIiLi1EEENS7_IhLi1EEEiES6_JS8_S9_iEJNS_4nameENS_5scopeENS_7siblingEA38_cNS_3argESH_NS_5arg_vEEEEvOT_PFT0_DpT1_EDpRKT2_ENKUlRNS_6detail13function_callEE1_clESW_[__ZZN8pybind1112cpp_function10initializeIRPFSt6vectorIS2_IiSaIiEESaIS4_EENS_7array_tIiLi1EEENS7_IhLi1EEEiES6_JS8_S9_iEJNS_4nameENS_5scopeENS_7siblingEA38_cNS_3argESH_NS_5arg_vEEEEvOT_PFT0_DpT1_EDpRKT2_ENKUlRNS_6detail13function_callEE1_clESW_]+0x66b): undefined reference to `_imp__PyErr_SetString'
C:\Users\Zebi\AppData\Local\Temp\ccum3Drs.o:pse.cpp:(.text$_ZZN8pybind1112cpp_function10initializeIRPFSt6vectorIS2_IiSaIiEESaIS4_EENS_7array_tIiLi1EEENS7_IhLi1EEEiES6_JS8_S9_iEJNS_4nameENS_5scopeENS_7siblingEA38_cNS_3argESH_NS_5arg_vEEEEvOT_PFT0_DpT1_EDpRKT2_ENKUlRNS_6detail13function_callEE1_clESW_[__ZZN8pybind1112cpp_function10initializeIRPFSt6vectorIS2_IiSaIiEESaIS4_EENS_7array_tIiLi1EEENS7_IhLi1EEEiES6_JS8_S9_iEJNS_4nameENS_5scopeENS_7siblingEA38_cNS_3argESH_NS_5arg_vEEEEvOT_PFT0_DpT1_EDpRKT2_ENKUlRNS_6detail13function_callEE1_clESW_]+0x671): undefined reference to `_imp__PyErr_Clear'
Makefile:10: recipe for target 'pse.so' failed
make: *** [pse.so] Error 1

**Comment by mpd847** [comment]
@liuheng92  can you please help me?? 
i change std=c++11 to std=gnu++11 and i getting all these errors

**Comment by liuheng92** [comment]
this code has not been tested under windows yet

**Comment by mpd847** [comment]
oh thank you so much , i am testing it on windows 10.  is there any way to compile pse.cpp under windows to generate pse_cpp

**Comment by ra1995** [comment]
Open the x64 or x32 Visual Studio devloper command prompt in Windows 10 and use the following command to generate the pse.pyd file:
first cd into pse folder
cl pse.cpp /I ./include /I "C:\Users\risha\Anaconda3\include" /LD /Fe:pse.pyd /link/LIBPATH:"C:\Users\risha\Anaconda3\libs"
comment line 8 and 9 of __init__.py

**Comment by JingCi-ZHu** [comment]
I have used the @ra1995  way to generate and get an obj file
![image](https://user-images.githubusercontent.com/45458068/60257267-b742b800-9905-11e9-8a7d-6202bee21178.png)
but i still have an error same as @mpd847 
![image](https://user-images.githubusercontent.com/45458068/60257313-ce81a580-9905-11e9-942c-7d8af3c9ddf2.png)
plz help
