### ISSUE TITLE
这段代码似乎有问题

### ISSUE THREAD

**Issue by afterimagex** [liuheng92/tensorflow_PSENet#23]
https://github.com/liuheng92/tensorflow_PSENet/blob/1afad501ac0af0a276b5850fcfed5f6e2f67cc09/utils/data_provider/data_provider.py#L297-L301

参见

https://github.com/novioleo/FOTS/blob/5d1a4fe822f498b9e6252dc19bf309d0e6a317f0/data_loader/datautils.py#L631-L643

**Comment by xxlxx1** [comment]
@afterimagex 没看明白，哪里有问题？
