### ISSUE TITLE
如何修改data_provider.py来支持多边形格式输入？

### ISSUE THREAD

**Issue by ZDDEAN** [liuheng92/tensorflow_PSENet#25]

**Comment by liuheng92** [comment]
修改输入前产生多边形标签的函数即可

**Comment by wuzuowuyou** [comment]
修改输入前产生多边形标签的函数
我的数据修改成任意点个数，但是训练的时候报错，如下：
tensorflow_PSENet-master/utils/data_provider/data_provider.py", line 87, in load_annoataion
    return np.array(text_polys, dtype=np.float32), np.array(text_tags, dtype=np.bool)
ValueError: setting an array element with a sequence.
好像是多线程读取，导致了text_polys里面的shape不一样了。。
想问下，如何解决

**Comment by lipeng1109** [comment]
> 修改输入前产生高标号标签的函数
> 我的数据修改成任意点个数，但是训练的时候报错，如下：
> tensorflow_PSENet-master / utils / data_provider / data_provider.py“，第87行，在load_annoataion
> 返回np.array（text_polys ，D型细胞= np.float32），np.array（text_tags，D型细胞= np.bool）
> ValueError异常：设置一个数组元素与序列
> 好像是多线程读取，导致了text_polys里面的形状不一样了..
> 想问下，如何解决

请问您解决了这个问题吗
