### ISSUE TITLE
Error loading model using downloaded files

### ISSUE THREAD

**Issue by DGM1193** [liuheng92/tensorflow_PSENet#29]
Thanks for sharing your work ! Looks very neat . 

I am trying to load the model provided and test it on my images. I  get this error when running the eval.py script. 
"InvalidArgumentError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Cannot assign a device for operation model_0/split: ...."

Could you please let me know what the issue is?

**Comment by liuheng92** [comment]
the graph from the checkpoint is as same as the graph from the code. I am sure about it. Maybe you can check your setting and running environment

**Comment by DGM1193** [comment]
Thanks for the quick response ! 
May I know which version of tensorflow you are usng to run this ?

**Comment by DGM1193** [comment]
Thanks for the quick reply ! I solved the previous error I had, and I get this error now : 

AttributeError: 'NoneType' object has no attribute 'model_checkpoint_path'

**Comment by liuheng92** [comment]
create a checkpoint file yourself

**Comment by DGM1193** [comment]
I solved this issue by replacing lines 169 to 173 in eval.py which is  :
```
        with tf.Session(config=tf.ConfigProto(allow_soft_placement=True)) as sess:
            ckpt_state = tf.train.get_checkpoint_state(FLAGS.checkpoint_path)
            model_path = os.path.join(FLAGS.checkpoint_path, os.path.basename(ckpt_state.model_checkpoint_path))
            logger.info('Restore from {}'.format(model_path))
saver.restore(sess, model_path)
```

with the following lines of code:
```
  with tf.Session(config=tf.ConfigProto(allow_soft_placement=True)) as sess:
            saver = tf.train.Saver()
            # saver = tf.train.import_meta_graph(model_path+'.meta')    # path to meta file 
            saver.restore(sess, model_path)    # path to ckpt file
```

and using tensorflow version 1.8

**Comment by JingCi-ZHu** [comment]
I have used @DGM1193  comment: replace eval.py like this
 tf.Session(config=tf.ConfigProto(allow_soft_placement=True)) as sess:
            saver = tf.train.Saver()
            saver.restore(sess, '~\checkpoint\model.ckpt') 
I  unziped files in repo and got three files.(model.ckpt.data-00000-of-00001)(model.ckpt.index)(model.ckpt.meta)
and fllow @liuheng92  create a blank .txt file rename to checkpoint
![image](https://user-images.githubusercontent.com/45458068/60251720-a4c38100-98fb-11e9-8e7e-02f3d528fa82.png)
and use :
python eval.py --test_data_path=./tmp/images/ --gpu_list=0 --checkpoint_path=./checkpoint/ --output_dir=./tmp/
in anaconda promote
get an error
![image](https://user-images.githubusercontent.com/45458068/60251450-21a22b00-98fb-11e9-9e1f-b9f38295691e.png)
I have searched this error,
![image](https://user-images.githubusercontent.com/45458068/60251632-780f6980-98fb-11e9-8a55-b18347cbb0fb.png)
I dont know what I should write in my own 'checkpoint' file
plz help
