### ISSUE TITLE
论文中的Lc区域用OHEM进行选择的，貌似代码里计算Lc部分没找到OHEM部分诶

### ISSUE THREAD

**Issue by xiaohuihuichao** [liuheng92/tensorflow_PSENet#30]

**Comment by liuheng92** [comment]
我没有加，我加过，效果不好就去了，也可能是我自己写的有问题，哈哈哈哈哈

**Comment by xiaohuihuichao** [comment]
那个model.py中的dice_coefficient损失计算函数，代码中貌似是2*S*G/(S*M+ G*M)，但是论文中是2*S*G/((S*M)^2 + (G*M)^2)，不知是否是有意为之

**Comment by xiaohuihuichao** [comment]
> 我没有加，我加过，效果不好就去了，也可能是我自己写的有问题，哈哈哈哈哈

另外，model.py中的dice_coefficient损失计算函数，代码中貌似是2S*G/(S*M+ G*M)，但是论文中是2*S*G/((S*M)^2 + (G*M)^2)，不知是否是有意为之

**Comment by liuheng92** [comment]
dice loss有很多形式，不是有意的
