### ISSUE TITLE
 model_path = os.path.join(FLAGS.checkpoint_path, os.path.basename(ckpt_state.model_checkpoint_path)) AttributeError: 'NoneType' object has no attribute 'model_checkpoint_path'

### ISSUE THREAD

**Issue by fang0607** [liuheng92/tensorflow_PSENet#32]
model_path = os.path.join(FLAGS.checkpoint_path, os.path.basename(ckpt_state.model_checkpoint_path))
AttributeError: 'NoneType' object has no attribute 'model_checkpoint_path'

does it because no checkpoint file in model? 
pls help

**Comment by DGM1193** [comment]
Refer to this link  on the issue I posted : https://github.com/liuheng92/tensorflow_PSENet/issues/29#issuecomment-502860505

It worked for me !

**Comment by fang0607** [comment]
NameError: name 'model_path' is not defined
a new error after replacement

**Comment by hiepph** [comment]
@fang0607 Create a `checkpoint` filename inside `model`  (extracted from model.targ.gz) with the following content:

```
model_checkpoint_path: "model.ckpt"
```
