### ISSUE TITLE
Single-Character detection failure.

### ISSUE THREAD

**Issue by SaiPrahladh** [liuheng92/tensorflow_PSENet#36]
While evaluating the results after considerable training, the model skips the single character detection part due to shrinked_poly function in data_provider.py line 234 causing the area of bounding boxes around single characters to go 0. Can anyone suggest the changes to be made in the code to work around this issue?

**Comment by SaiPrahladh** [comment]
The issue has been solved! I am closing this now.

**Comment by sihangsong** [comment]
> The issue has been solved! I am closing this now.

How did you solve it? Would you mind sharing your ideas? Thanks

**Comment by psnow** [comment]
@SaiPrahladh How to solved?Can you describe the process in detail
