### ISSUE TITLE
[eval.py] Should the evaluation script clip to the original width and height?

### ISSUE THREAD

**Issue by sdll** [liuheng92/tensorflow_PSENet#37]
I was going over the evaluation script and noticed that in the end boxes [are clipped](https://github.com/liuheng92/tensorflow_PSENet/blob/master/eval.py#L203) to the resized image size, which seems strange. Shouldn't text boxes fit the original image size instead?

**Comment by liuheng92** [comment]
Because input image is resized, I dont think it is strange.

**Comment by sdll** [comment]
@liuheng92, I am not saying that the resize is strange, rather what we resize to does not seem to make sense. Shouldn’t the boxes get clipped to the size of the original image instead, rather than the size of the resized image?

**Comment by liuheng92** [comment]
oh, I see. It is original image size which I had use. see [this line](https://github.com/liuheng92/tensorflow_PSENet/blob/1afad501ac0af0a276b5850fcfed5f6e2f67cc09/eval.py#L202)

**Comment by sdll** [comment]
Thanks, sorry for the confusion, seems so stupid in retrospect. Closing the issue.
