### ISSUE TITLE
[meta]: Adding license

### ISSUE THREAD

**Issue by sdll** [liuheng92/tensorflow_PSENet#38]
@liuheng92, thank you for your work! To enable others use your code for other projects, could you please add a license to your repo, explaining the conditions for fair use? Since the PyTorch implementation is [licensed](https://github.com/whai362/PSENet/blob/master/LICENSE) with Apache 2.0, this would look great from the legal side as well. I appreciate your time!

**Comment by liuheng92** [comment]
already added, thank you for your remind.

**Comment by liuheng92** [comment]
> @liuheng92, thank you for your work! To enable others use your code for other projects, could you please add a license to your repo, explaining the conditions for fair use? Since the PyTorch implementation is [licensed](https://github.com/whai362/PSENet/blob/master/LICENSE) with Apache 2.0, this would look great from the legal side as well. I appreciate your time!

already added, thank you for your advice.
