### ISSUE TITLE
one question

### ISSUE THREAD

**Issue by zhaojc001** [liuheng92/tensorflow_PSENet#4]
when i test,it appears the following error,please help me:
Traceback (most recent call last):
  File "eval.py", line 235, in <module>
    tf.app.run()
  File "/root/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "eval.py", line 171, in main
    model_path = os.path.join(FLAGS.checkpoint_path, os.path.basename(ckpt_state.model_checkpoint_path))
AttributeError: 'NoneType' object has no attribute 'model_checkpoint_path'

**Comment by XXRRL** [comment]
> when i test,it appears the following error,please help me:
> Traceback (most recent call last):
> File "eval.py", line 235, in 
> tf.app.run()
> File "/root/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
> _sys.exit(main(_sys.argv[:1] + flags_passthrough))
> File "eval.py", line 171, in main
> model_path = os.path.join(FLAGS.checkpoint_path, os.path.basename(ckpt_state.model_checkpoint_path))
> AttributeError: 'NoneType' object has no attribute 'model_checkpoint_path'
add a checkpoint file

**Comment by NormalAppler** [comment]
I have the same question，so Where can I get the checkpoint file?

**Comment by XXRRL** [comment]
Write one by yourself

**Comment by liuheng92** [comment]
or, you can modify modelpath in eval.py

**Comment by 411066282** [comment]
Dear author, could you be more specific about this issue?

**Comment by liuheng92** [comment]
> Dear author, could you be more specific about this issue?

model_path='(add your model path).ckpt'
