### ISSUE TITLE
Single character detection missing

### ISSUE THREAD

**Issue by huynhthedang** [liuheng92/tensorflow_PSENet#40]
Hi,

Thanks for the great work!
I encounter a problem with the code where single characters could not be detected. I found a similar issue and it seems not to be resolved https://github.com/liuheng92/tensorflow_PSENet/issues/36

Could anyone suggest a solution for detecting single characters? Thanks.

**Comment by SaiPrahladh** [comment]
> Hi,
> 
> Thanks for the great work!
> I encounter a problem with the code where single characters could not be detected. I found a similar issue and it seems not to be resolved #36
> 
> Could anyone suggest a solution for detecting single characters? Thanks.

**Comment by SaiPrahladh** [comment]
@huynhthedang The cause of the model skipping single characters is in the eval.py file, you have to look for minimum character size threshold, it might be set to '10', try lowering the threshold and run eval again. This should solve your issue.
