### ISSUE TITLE
'NoneType' object has no attribute 'model_checkpoint_path'

### ISSUE THREAD

**Issue by banbsyip** [liuheng92/tensorflow_PSENet#46]
sas@sas-virtual-machine:~/桌面/tensorflow_PSENet-master$ python3 eval.py 
DEBUG:matplotlib.pyplot:Loaded backend qt5agg version unknown.
DEBUG:matplotlib.pyplot:Loaded backend qt5agg version unknown.
DEBUG:matplotlib.pyplot:Loaded backend Qt5Agg version unknown.
/home/sas/桌面/tensorflow_PSENet-master/pse ll
make: 进入目录“/home/sas/桌面/tensorflow_PSENet-master/pse”
make: “pse.so”已是最新。
make: 离开目录“/home/sas/桌面/tensorflow_PSENet-master/pse”
resnet_v1_50/block1 (?, ?, ?, 256)
resnet_v1_50/block2 (?, ?, ?, 512)
resnet_v1_50/block3 (?, ?, ?, 1024)
resnet_v1_50/block4 (?, ?, ?, 2048)
2019-09-18 20:55:14.255332: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "eval.py", line 237, in <module>
    tf.app.run()
  File "/home/sas/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "eval.py", line 173, in main
    model_path = os.path.join(FLAGS.checkpoint_path, os.path.basename(ckpt_state.model_checkpoint_path))
AttributeError: 'NoneType' object has no attribute 'model_checkpoint_path'
这里出现了'NoneType' object has no attribute 'model_checkpoint_path'的问题，不知道是何问题？

**Comment by tejanmehndiratta** [comment]
I am having the same issue

**Comment by banbsyip** [comment]
> I am having the same issue

I had resolved this problem.
in lines 13 of eval.py:
tf.app.flags.DEFINE_string('checkpoint_path', './', '')
this line code in my demo is:
tf.app.flags.DEFINE_string('checkpoint_path', './resnet_v1_50/model.ckpt', '')
if you model named just like "model.ckpt.data-00000-of-00001"(model.ckpt.XXX)  you should add the "model.ckpt" to the absolute path or relative path.

**Comment by tejanmehndiratta** [comment]
I am in a conundrum. Should I rename  "model.ckpt.data-00000-of-00001" to "model.ckpt" and then do this: tf.app.flags.DEFINE_string('checkpoint_path', './resnet_v1_50/model.ckpt', '') ?

**Comment by banbsyip** [comment]
> I am in a conundrum. Should I rename  "model.ckpt.data-00000-of-00001" to "model.ckpt" and then do this: tf.app.flags.DEFINE_string('checkpoint_path', './resnet_v1_50/model.ckpt', '') ?

you don't need, the type of model's name is xxx.yyy.zzz. you just need add the xxx.yyy to the path. such as if your model named"model.ckpt-1.data-00000-of-00001",you just add the model.ckpt-1 to path

**Comment by amdslgl** [comment]
> I am having the same issue
> 
> I had resolved this problem.
> in lines 13 of eval.py:
> tf.app.flags.DEFINE_string('checkpoint_path', './', '')
> this line code in my demo is:
> tf.app.flags.DEFINE_string('checkpoint_path', './resnet_v1_50/model.ckpt', '')
> if you model named just like "model.ckpt.data-00000-of-00001"(model.ckpt.XXX)  you should add the "model.ckpt" to the absolute path or relative path.

I have changed the checkpoint_path,but it is still reporting None type error,please help me ,please

**Comment by banbsyip** [comment]
> > I am having the same issue
> > I had resolved this problem.
> > in lines 13 of eval.py:
> > tf.app.flags.DEFINE_string('checkpoint_path', './', '')
> > this line code in my demo is:
> > tf.app.flags.DEFINE_string('checkpoint_path', './resnet_v1_50/model.ckpt', '')
> > if you model named just like "model.ckpt.data-00000-of-00001"(model.ckpt.XXX)  you should add the "model.ckpt" to the absolute path or relative path.
> 
> I have changed the checkpoint_path,but it is still reporting None type error,please help me ,please

you should change the path in two lines code. that the follows:
![image](https://user-images.githubusercontent.com/18277076/67022480-df178f00-f133-11e9-9b04-3bf2de66ad32.png)
![image](https://user-images.githubusercontent.com/18277076/67022296-952ea900-f133-11e9-815c-35abea8feace.png)
i hope it can help you!

**Comment by yuxiaomu** [comment]
@banbsyip 
我有同样的问题,按照您的方法改了,提示下面这样ValueError: The passed save_path is not a valid checkpoint: ./resnet_v1_50/model.ckpt,您只到哪里的问题吗,我的模型保存在/home/yyk/PycharmProjects/untitled1/tensorflow_PSENet-master/mymodel/model.ckpt-56561.data-00000-of-00001的路径下

**Comment by banbsyip** [comment]
> @banbsyip
> 我有同样的问题,按照您的方法改了,提示下面这样ValueError: The passed save_path is not a valid checkpoint: ./resnet_v1_50/model.ckpt,您只到哪里的问题吗,我的模型保存在/home/yyk/PycharmProjects/untitled1/tensorflow_PSENet-master/mymodel/model.ckpt-56561.data-00000-of-00001的路径下

这个要按照你的路径来啊，别光照抄的我的路径和文件名，我的只是样例，你得按你自己的实际情况来改，相对路径和绝对路径都行。看你的文件名你这个训练到56561轮了，可我只训练到第六轮就训练不下去了，能交流一下训练的情况吗？

**Comment by amdslgl** [comment]
> 
> 
> > > I am having the same issue
> > > I had resolved this problem.
> > > in lines 13 of eval.py:
> > > tf.app.flags.DEFINE_string('checkpoint_path', './', '')
> > > this line code in my demo is:
> > > tf.app.flags.DEFINE_string('checkpoint_path', './resnet_v1_50/model.ckpt', '')
> > > if you model named just like "model.ckpt.data-00000-of-00001"(model.ckpt.XXX)  you should add the "model.ckpt" to the absolute path or relative path.
> > 
> > 
> > I have changed the checkpoint_path,but it is still reporting None type error,please help me ,please
> 
> you should change the path in two lines code. that the follows:
> ![image](https://user-images.githubusercontent.com/18277076/67022480-df178f00-f133-11e9-9b04-3bf2de66ad32.png)
> ![image](https://user-images.githubusercontent.com/18277076/67022296-952ea900-f133-11e9-815c-35abea8feace.png)
> i hope it can help you

> 
> 
> > > I am having the same issue
> > > I had resolved this problem.
> > > in lines 13 of eval.py:
> > > tf.app.flags.DEFINE_string('checkpoint_path', './', '')
> > > this line code in my demo is:
> > > tf.app.flags.DEFINE_string('checkpoint_path', './resnet_v1_50/model.ckpt', '')
> > > if you model named just like "model.ckpt.data-00000-of-00001"(model.ckpt.XXX)  you should add the "model.ckpt" to the absolute path or relative path.
> > 
> > 
> > I have changed the checkpoint_path,but it is still reporting None type error,please help me ,please
> 
> you should change the path in two lines code. that the follows:
> ![image](https://user-images.githubusercontent.com/18277076/67022480-df178f00-f133-11e9-9b04-3bf2de66ad32.png)
> ![image](https://user-images.githubusercontent.com/18277076/67022296-952ea900-f133-11e9-815c-35abea8feace.png)
> i hope it can help you!
the code runs  smoothly because of your assistance.so gratful appreciation for you

**Comment by liuheng92** [comment]
please see  (#32)[https://github.com/liuheng92/tensorflow_PSENet/issues/32]

**Comment by MichaelHL-ai** [comment]
please see #32
