### ISSUE TITLE
Error while running script please help!

### ISSUE THREAD

**Issue by nbhupendra** [liuheng92/tensorflow_PSENet#49]
tf.app.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "eval.py", line 171, in main
    model_path = os.path.join(FLAGS.checkpoint_path, os.path.basename(ckpt_state.model_checkpoint_path))
AttributeError: 'NoneType' object has no attribute 'model_checkpoint_path'

running below command-
 python3.6 eval.py --test_data_path=./tmp/images/ --gpu_list=0 --checkpoint_path=./resnet_v1_50/--output_dir=./tmp/

Note- I have resnet_v1_50.ckpt file under resnet_v1_50 directory. 

Please help.;

**Comment by anmol4210** [comment]
remove os.path.basename(ckpt_state.model_checkpoint_path))

**Comment by MichaelHL-ai** [comment]
#32
