### ISSUE TITLE
a error raise on python3.6+TF1.11Gpu

### ISSUE THREAD

**Issue by hhliao** [liuheng92/tensorflow_PSENet#5]
from .pse import pse_cpp
ImportError: dynamic module does not define module export function (PyInit_pse)

**Comment by liuheng92** [comment]
modify makefile，read readme for reference

**Comment by hhliao** [comment]
yes, I modified the Makefile, and still raise a error:
g++: error: unrecognized command line option ‘-fno-plt’
The changelog page for GCC 6 says: The option -fno-plt is now fully functional. 
But how to fix it for GCC 4.8?

**Comment by liuheng92** [comment]
g++ 6? I have tried 4.2 , 4.8 and 5.2.

**Comment by hhliao** [comment]
I have fixed this problem from https://github.com/argman/EAST/issues/156

**Comment by Tian14267** [comment]
How should I modified the Makefile ? I get same error in pse_cpp . can you tell me in detail @hhliao
