### ISSUE TITLE
when can I stop the training

### ISSUE THREAD

**Issue by li10141110** [liuheng92/tensorflow_PSENet#52]
<img width="727" alt="Screen Shot 2019-10-16 at 10 54 41 AM" src="https://user-images.githubusercontent.com/26408067/66884330-6fa28200-f003-11e9-9d05-a7ea46fc84fe.png">
when should I stop my customed training? Any help?

**Comment by li10141110** [comment]
CUDA_VISIBLE_DEVICES=0,1,2,3 python train.py --gpu_list=0,1,2,3 --input_size=512 --batch_size_per_gpu=16 --checkpoint_path=./resnet_train --training_data_path=/home/data/disk/all_api_imgs

**Comment by MichaelHL-ai** [comment]
see #44
