### ISSUE TITLE
How to load pre_trained model?

### ISSUE THREAD

**Issue by ceciliaAI** [liuheng92/tensorflow_PSENet#55]

**Comment by ceciliaAI** [comment]
I used your code to train my own dataset. Now I want to load the trained model for fine-tuning. The currently saved model has models of .index and .data types. How to load it?

**Comment by MichaelHL-ai** [comment]
use tf.train.Saver, you can read [tensorflow api](https://www.tensorflow.org/versions/r1.13/api_docs/python/tf/train/Saver) for more infos
