### ISSUE TITLE
使用pretrained模型在icdar2015上复现出来结果不一致

### ISSUE THREAD

**Issue by alexwangmac** [liuheng92/tensorflow_PSENet#58]
首先感谢@liuheng92的awesome work! 有个问题希望请教下：
使用pretrained模型评估的结果为 "precision": 0.7663398692810458, "recall": 0.6774193548387096, "F-mean": 0.7191413237924866
和@liuheng92 展示的结果对不上，recall要差很多，请问下可能的原因是什么？

**Comment by 1994sugar** [comment]
您好！请教一下，您这些指标是在哪里测得的呢？

**Comment by 1994sugar** [comment]
> 首先感谢@liuheng92的awesome work! 有个问题希望请教下：
> 使用pretrained模型评估的结果为 "precision": 0.7663398692810458, "recall": 0.6774193548387096, "F-mean": 0.7191413237924866
> 和@liuheng92 展示的结果对不上，recall要差很多，请问下可能的原因是什么？

同学您好！我使用预训练训练出来的结果比你的还差...
"recall": 0.7168993740972557, "precision": 0.6716283265674334, "hmean": 0.6935258500232883

**Comment by cyLVlyl** [comment]
你好  我也直接用的预训练模型  出来的结果跟你一样 请问你知道是什么原因了吗 @alexwangmac

**Comment by 1994sugar** [comment]
> 你好 我也直接用的预训练模型 出来的结果跟你一样 请问你知道是什么原因了吗 @alexwangmac
您好！可以加下qq吗？向您请教一下问题

**Comment by cyLVlyl** [comment]
> > 你好 我也直接用的预训练模型 出来的结果跟你一样 请问你知道是什么原因了吗 @alexwangmac
> > 您好！可以加下qq吗？向您请教一下问题

我是小白  怕帮不了你。。你说下qq  我加你

**Comment by 1994sugar** [comment]
> > > 你好 我也直接用的预训练模型 出来的结果跟你一样 请问你知道是什么原因了吗 @alexwangmac
> > > 您好！可以加下qq吗？向您请教一下问题
> 
> 我是小白 怕帮不了你。。你说下qq 我加你

296055705 谢谢

**Comment by cyLVlyl** [comment]
> > > > 你好 我也直接用的预训练模型 出来的结果跟你一样 请问你知道是什么原因了吗 @alexwangmac
> > > > 您好！可以加下qq吗？向您请教一下问题
> > 
> > 
> > 我是小白 怕帮不了你。。你说下qq 我加你
> 
> 296055705 谢谢

我加了

**Comment by 1994sugar** [comment]
> > > > > 你好 我也直接用的预训练模型 出来的结果跟你一样 请问你知道是什么原因了吗 @alexwangmac
> > > > > 您好！可以加下qq吗？向您请教一下问题
> > > 
> > > 
> > > 我是小白 怕帮不了你。。你说下qq 我加你
> > 
> > 
> > 296055705 谢谢
> 
> 我加了

好的，我现在还没收到验证消息，qq:296055705

**Comment by MichaelHL-ai** [comment]
@alexwangmac 设置一下后处理的阈值

**Comment by guweixin** [comment]
请问具体是哪部分阈值，设置成多少？和论文一样么？
