### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by amyjim9907** [liuheng92/tensorflow_PSENet#63]
想请问:
在跑训练的过程中没有error但出现以下状况看起来是还没开始训练，我使用的data格式与icdar 2017相同，检查图片路径没有错误，猜测应该是在data_provider.py上出问题，但找了很久还无法解决
![image](https://user-images.githubusercontent.com/22467615/71051299-d4ed2d80-2182-11ea-96f8-dcf1c625d287.png)
![image](https://user-images.githubusercontent.com/22467615/71051305-dae30e80-2182-11ea-8897-cad0d5732f62.png)

**Comment by MichaelHL-ai** [comment]
如何解决的

**Comment by MichaelHL-ai** [comment]
@amyjim9907

**Comment by amyjim9907** [comment]
@liuheng92 後來發現是讀檔編碼問題
data_provider.py中
修改load_annoatation(p):
with open(p,'r')---->改為with open(p,'r',encoding='utf8')
