### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'model_checkpoint_path'

### ISSUE THREAD

**Issue by shwaitkumar** [liuheng92/tensorflow_PSENet#77]
File "eval.py", line 171, in main
    model_path = os.path.join(FLAGS.checkpoint_path, os.path.basename(ckpt_state.model_checkpoint_path))
AttributeError: 'NoneType' object has no attribute 'model_checkpoint_path'

**Comment by daniperfer** [comment]
I've seen a solution to this in https://github.com/liuheng92/tensorflow_PSENet/issues/32
