### ISSUE TITLE
Not able to download pretrained model 

### ISSUE THREAD

**Issue by Lahirevinod** [liuheng92/tensorflow_PSENet#8]
Can we get Drive share ... on the given link you have to download app and login first .
Is there any work around for this ?. it's getting difficult for non-china user to explore PSENet .

**Comment by dsandii** [comment]
Since you closed this, were you able to get the pretrained model from a different source?

**Comment by liuheng92** [comment]
> Since you closed this, were you able to get the pretrained model from a different source?

sorry, but I didn't close this issue, I've updated readme
