### ISSUE TITLE
标签中的True和False不太理解

### ISSUE THREAD

**Issue by Ri-Yue-Shui-Hua** [liuheng92/tensorflow_PSENet#85]
if label == '*' or label == '###' or label == '?':
                text_tags.append(True)
            else:
                text_tags.append(False)
这段代码是说，坐标后面的字符 只有是 “*” 或者“ ###” 或者“？”时才标注为True，其他都标注为False。
但是我看icdar2015标注数据都写得是 **数字**或者**单词词组**，并不是上面提到的这些。
求指教。

**Comment by MichaelHL-ai** [comment]
这些指的是模棱两可的标注，不会用来训练
