### ISSUE TITLE
tf.train.get_checkpoint_state('/home/yons/models')  加载模型不起作用？？

### ISSUE THREAD

**Issue by caozhongbjtu** [liuheng92/tensorflow_PSENet#88]
![2020-09-17 10-31-21 的屏幕截图](https://user-images.githubusercontent.com/50758437/93413184-45230e00-f8d1-11ea-9ee3-cbf49261e1d2.png)
在eval.py文件中，tensorflow加载模型tf.train.get_checkpoint_state('/home/yons/models')无法检测到chechpoint，这是咋回事？？是我的tensorflow版本问题吗？我的tensorflow版本是1.12

**Comment by MichaelHL-ai** [comment]
https://github.com/liuheng92/tensorflow_PSENet/issues/29
