### ISSUE TITLE
中文训练

### ISSUE THREAD

**Issue by NormalAppler** [liuheng92/tensorflow_PSENet#9]
作者，你好，请问你的训练模型，没有在中文训练集上训练过吗？我再中文图片上感觉效果不好，打算在中文数据集比如天池数据上进行训练，是否可行？需要哪些注意的地方

**Comment by liuheng92** [comment]
这个模型没用中文数据库，当然可以用中文数据库训练，检测中英文没有什么特殊的地方，可以直接使用

**Comment by NormalAppler** [comment]
ok，谢谢
